language: elixir
elixir:
 - 1.4.1
addons:
  postgresql: '9.4'
before_install: cd /home/travis/build/dwyl/learn-phoenix-framework/rumbrella && pwd
cache:
  directories:
    - _build
    - deps
env:
  - MIX_ENV=test
before_script:
  - mix do ecto.create
script:
  - mix do deps.get, compile --warnings-as-errors, coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
